### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by Timopheym** [deepmipt/Pilot#8]
Sorry guys, i am kinda crazy, and trying runing pilot on windows, but so far i even can't get some required files, f.e. on
```
>python deep.py interact skills/hcn_new/config.json
```
i am getting error
```
deeppavlov.core.common.errors.ConfigError: "Provided ser_path doesn't exist!"
```
Where can i get ```word_vocab.dict```?

thanks!

**Comment by vikmary** [comment]
It is not the issue of running on Windows, the same error raises on Linux.

The documentation and config files are still not ready for use. Fully functional library version will be released soon.

**Comment by Timopheym** [comment]
@vikmary I know it's not, i have issues with compiling 
fasttext==0.8.3
kenlm==0.0.0 on windows, but i think i can figure it out, 
I just want some start code to play with and extend. Currently i am planning architecture for my DPA, and DeepPavlov looks promising, but i can't see the full picture =(

**Comment by vikmary** [comment]
> i am getting error
>```
>deeppavlov.core.common.errors.ConfigError: "Provided ser_path doesn't exist!"
>```
The error means that all directories from `ser_path`'s in your config must already exist.

And it is raised because interaction with `hcn_new` expects that you have already pretrained named entity recognition model (see [`models/ner`](https://github.com/deepmipt/Pilot/blob/master/deeppavlov/models/ner)), intents classifier (see [`models/classifiers/intents`](https://github.com/deepmipt/Pilot/blob/master/deeppavlov/classifiers/intents))  and hybrid code network model itself (see [`skills/hcn_new`](https://github.com/deepmipt/Pilot/blob/master/deeppavlov/skills/hcn_new)).

I recommend you to wait until we upload pretrained model files. Or you can train `models/ner/config.json` and `models/classifiers/intents/config.json` in order to be able to then train and use `skills/hcn_new/config.json`.

>Where can i get `word_vocab.dict`?

`word_vocab.dict` will be created during `hcn_new` training.
